# Site settings
title: "Dao Tuan Viet"
description: "Resume"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vietdt89.github.io"
# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Dao Tuan Viet"
resume_title:                   "Automotive Software Engineer"

# used for the contact button in _layouts/resume.html
#resume_contact_email:           ""

# the next two items are used for schema itemprops in _layouts/resume.html
#resume_contact_telephone:       ""
#resume_contact_address:         ""

#resume_header_contact_info:     ""
display_header_contact_info:    "false"

resume_header_intro: "<p>Embedded Engineer with over 10 years of experience in software development. 
Significant management experience, including leading a team of up to 20 individuals. 
Excellent history of delivering products to leading automotive OEMs, with background building Linux/QNX apps, debugging and monitoring quality, and handling change requests. 
Key strengths include leadership, project management, training, and process improvement.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      false
resume_section_education:       false
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  #resume_github_url:            "https://github.com/jglovier/resume-template"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://vietdt89.hashnode.dev/"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/daotuanviet/"
  #resume_instagram_url:         "https://vietdt89.hashnode.dev/"
  resume_website_url:           "https://viettuandao.substack.com/"
  #resume_medium_url:            "https://dev.to/vietdt89"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
